# Generated by Django 4.0.4 on 2022-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.IngredientInRecipe', to='recipes.ingredient', verbose_name='Список ингредиентов'),
        ),
    ]
